/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransactionsRouteImport } from './routes/_app.transactions'
import { Route as AppSummaryRouteImport } from './routes/_app.summary'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppIncomeRouteImport } from './routes/_app.income'
import { Route as AppExportRouteImport } from './routes/_app.export'
import { Route as AppExpenseRouteImport } from './routes/_app.expense'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBudgetRouteImport } from './routes/_app.budget'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSummaryRoute = AppSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppExpenseRoute = AppExpenseRouteImport.update({
  id: '/expense',
  path: '/expense',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/budget': typeof AppBudgetRoute
  '/dashboard': typeof AppDashboardRoute
  '/expense': typeof AppExpenseRoute
  '/export': typeof AppExportRoute
  '/income': typeof AppIncomeRoute
  '/reports': typeof AppReportsRoute
  '/summary': typeof AppSummaryRoute
  '/transactions': typeof AppTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/budget': typeof AppBudgetRoute
  '/dashboard': typeof AppDashboardRoute
  '/expense': typeof AppExpenseRoute
  '/export': typeof AppExportRoute
  '/income': typeof AppIncomeRoute
  '/reports': typeof AppReportsRoute
  '/summary': typeof AppSummaryRoute
  '/transactions': typeof AppTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/signup': typeof SignupRoute
  '/_app/budget': typeof AppBudgetRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expense': typeof AppExpenseRoute
  '/_app/export': typeof AppExportRoute
  '/_app/income': typeof AppIncomeRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/summary': typeof AppSummaryRoute
  '/_app/transactions': typeof AppTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/budget'
    | '/dashboard'
    | '/expense'
    | '/export'
    | '/income'
    | '/reports'
    | '/summary'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/budget'
    | '/dashboard'
    | '/expense'
    | '/export'
    | '/income'
    | '/reports'
    | '/summary'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/signup'
    | '/_app/budget'
    | '/_app/dashboard'
    | '/_app/expense'
    | '/_app/export'
    | '/_app/income'
    | '/_app/reports'
    | '/_app/summary'
    | '/_app/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/summary': {
      id: '/_app/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AppSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expense': {
      id: '/_app/expense'
      path: '/expense'
      fullPath: '/expense'
      preLoaderRoute: typeof AppExpenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBudgetRoute: typeof AppBudgetRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpenseRoute: typeof AppExpenseRoute
  AppExportRoute: typeof AppExportRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSummaryRoute: typeof AppSummaryRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetRoute: AppBudgetRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpenseRoute: AppExpenseRoute,
  AppExportRoute: AppExportRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppReportsRoute: AppReportsRoute,
  AppSummaryRoute: AppSummaryRoute,
  AppTransactionsRoute: AppTransactionsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
